"""Change columns name and dob to username and date_of_birth in users table

Revision ID: 3cce66436996
Revises: 
Create Date: 2025-05-13 14:28:16.017225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cce66436996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=False))
        batch_op.drop_index('ix_users_name')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        batch_op.drop_column('name')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_name', ['name'], unique=False)
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
