"""Add jwt token support

Revision ID: 995966f198f8
Revises: de7ceadd0f5b
Create Date: 2025-05-02 02:03:30.493363

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "995966f198f8"
down_revision = "de7ceadd0f5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("dob", existing_type=sa.DATE(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("dob", existing_type=sa.DATE(), nullable=True)

    # ### end Alembic commands ###
