"""Fresh Start

Revision ID: ba102dfbc547
Revises: 
Create Date: 2025-05-03 22:30:53.067275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba102dfbc547"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("department_name", sa.String(), nullable=False),
        sa.Column("department_location", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("department_name"),
    )
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_departments_id"), ["id"], unique=False)

    op.create_table(
        "roles",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_roles_id"), ["id"], unique=False)

    op.create_table(
        "uploaded_files",
        sa.Column("file_name", sa.String(length=100), nullable=False),
        sa.Column("file_url", sa.String(length=1000), nullable=False),
        sa.Column("file_type", sa.String(length=10), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("uploaded_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_uploaded_files_id"), ["id"], unique=False)

    op.create_table(
        "rooms",
        sa.Column("room_location", sa.String(), nullable=False),
        sa.Column("department_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_location"),
    )
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rooms_id"), ["id"], unique=False)

    op.create_table(
        "users",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("gender", sa.Enum("M", "F", name="gender_enum"), nullable=False),
        sa.Column("ssn", sa.String(length=14), nullable=False),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("role_id", sa.String(length=128), nullable=False),
        sa.Column("pic_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pic_id"],
            ["uploaded_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_role_id"), ["role_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_ssn"), ["ssn"], unique=False)

    op.create_table(
        "admins",
        sa.Column("is_superadmin", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admins_id"), ["id"], unique=False)

    op.create_table(
        "doctors",
        sa.Column("years_of_experience", sa.Integer(), nullable=False),
        sa.Column("salary", sa.Float(), nullable=False),
        sa.Column("date_of_hire", sa.Date(), nullable=False),
        sa.Column("major", sa.String(length=100), nullable=False),
        sa.Column("department_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("doctors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_doctors_id"), ["id"], unique=False)

    op.create_table(
        "medical_devices",
        sa.Column("medical_device_name", sa.String(length=30), nullable=False),
        sa.Column("room_id", sa.String(length=128), nullable=False),
        sa.Column("medical_device_price", sa.Float(), nullable=False),
        sa.Column("medical_device_state", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medical_devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_medical_devices_id"), ["id"], unique=False)

    op.create_table(
        "patients",
        sa.Column(
            "blood_type",
            sa.Enum(
                "A_POS",
                "A_NEG",
                "B_POS",
                "B_NEG",
                "AB_POS",
                "AB_NEG",
                "O_POS",
                "O_NEG",
                name="bloodtype",
            ),
            nullable=True,
        ),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_patients_blood_type"), ["blood_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_patients_id"), ["id"], unique=False)

    op.create_table(
        "phone_numbers",
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("number", sa.String(length=11), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    with op.batch_alter_table("phone_numbers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_phone_numbers_id"), ["id"], unique=False)

    op.create_table(
        "appointments",
        sa.Column("patient_id", sa.String(length=128), nullable=False),
        sa.Column("doctor_id", sa.String(length=128), nullable=False),
        sa.Column("appointment_date_time", sa.DateTime(), nullable=False),
        sa.Column("room_id", sa.String(length=128), nullable=True),
        sa.Column("file_id", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["uploaded_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_appointments_id"), ["id"], unique=False)

    op.create_table(
        "dependents",
        sa.Column("dependent_name", sa.String(length=100), nullable=False),
        sa.Column("relationship", sa.String(length=50), nullable=False),
        sa.Column("dependent_phone_number", sa.String(length=11), nullable=False),
        sa.Column("patient_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dependents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dependents_id"), ["id"], unique=False)

    op.create_table(
        "medical_history",
        sa.Column("disease_name", sa.String(length=100), nullable=False),
        sa.Column("family_history", sa.Boolean(), nullable=True),
        sa.Column("patient_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medical_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_medical_history_disease_name"),
            ["disease_name"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_medical_history_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_medical_history_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "working_slots",
        sa.Column("doctor_id", sa.String(length=128), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column(
            "day",
            sa.Enum(
                "SUNDAY",
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                name="dayofweek",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("end_time > start_time", name="check_time_validity"),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("working_slots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_working_slots_day"), ["day"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_working_slots_doctor_id"), ["doctor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_working_slots_end_time"), ["end_time"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_working_slots_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_working_slots_start_time"), ["start_time"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("working_slots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_working_slots_start_time"))
        batch_op.drop_index(batch_op.f("ix_working_slots_id"))
        batch_op.drop_index(batch_op.f("ix_working_slots_end_time"))
        batch_op.drop_index(batch_op.f("ix_working_slots_doctor_id"))
        batch_op.drop_index(batch_op.f("ix_working_slots_day"))

    op.drop_table("working_slots")
    with op.batch_alter_table("medical_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medical_history_patient_id"))
        batch_op.drop_index(batch_op.f("ix_medical_history_id"))
        batch_op.drop_index(batch_op.f("ix_medical_history_disease_name"))

    op.drop_table("medical_history")
    with op.batch_alter_table("dependents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dependents_id"))

    op.drop_table("dependents")
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointments_id"))

    op.drop_table("appointments")
    with op.batch_alter_table("phone_numbers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_phone_numbers_id"))

    op.drop_table("phone_numbers")
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patients_id"))
        batch_op.drop_index(batch_op.f("ix_patients_blood_type"))

    op.drop_table("patients")
    with op.batch_alter_table("medical_devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medical_devices_id"))

    op.drop_table("medical_devices")
    with op.batch_alter_table("doctors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doctors_id"))

    op.drop_table("doctors")
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admins_id"))

    op.drop_table("admins")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_ssn"))
        batch_op.drop_index(batch_op.f("ix_users_role_id"))
        batch_op.drop_index(batch_op.f("ix_users_name"))
        batch_op.drop_index(batch_op.f("ix_users_id"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("rooms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rooms_id"))

    op.drop_table("rooms")
    with op.batch_alter_table("uploaded_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploaded_files_id"))

    op.drop_table("uploaded_files")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_id"))

    op.drop_table("roles")
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_departments_id"))

    op.drop_table("departments")
    # ### end Alembic commands ###
