"""add relationship field to the dependent table

Revision ID: ff3e35f426c3
Revises: 24c5b563cf97
Create Date: 2025-05-02 22:37:56.908417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff3e35f426c3"
down_revision = "24c5b563cf97"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dependents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("relationship", sa.String(length=50), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dependents", schema=None) as batch_op:
        batch_op.drop_column("relationship")

    # ### end Alembic commands ###
